/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ml_dmlc_xgboost4j_java_XGBoostSparkJNI */

#ifndef _Included_ml_dmlc_xgboost4j_java_XGBoostSparkJNI
#define _Included_ml_dmlc_xgboost4j_java_XGBoostSparkJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostSparkJNI
 * Method:    buildUnsafeRows
 * Signature: ([J[J[IJ)J
 */
JNIEXPORT jlong JNICALL Java_ml_dmlc_xgboost4j_java_XGBoostSparkJNI_buildUnsafeRows
  (JNIEnv *, jclass, jlongArray, jlongArray, jintArray, jlong);

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostSparkJNI
 * Method:    getGpuDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_xgboost4j_java_XGBoostSparkJNI_getGpuDevice
  (JNIEnv *, jclass);

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostSparkJNI
 * Method:    allocateGpuDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_xgboost4j_java_XGBoostSparkJNI_allocateGpuDevice
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
