# Configure R package builds to use sccache.
#
# Pass --cmake to configure CMake launchers instead,to avoid selecting an sccache-wrapped
# CXX as NVCC's host compiler.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 1L || (length(args) == 1L && args[[1L]] != "--cmake")) {
  stop("Usage: setup_r_sccache.R [--cmake]", call. = FALSE)
}
use_cmake <- length(args) == 1L
header <- "# Generated by XGBoost CI setup_r_sccache.R"

makevars <- file.path(path.expand("~"), ".R", "Makevars")
if (file.exists(makevars)) {
  first_line <- readLines(makevars, n = 1L, warn = FALSE)
  if (!identical(first_line, header)) {
    stop(
      makevars,
      " already exists; aborting to avoid overwriting it.",
      call. = FALSE
    )
  }
}

dir.create(dirname(makevars), recursive = TRUE, showWarnings = FALSE)
if (use_cmake) {
  settings <- c(
    header,
    "CMAKE_C_COMPILER_LAUNCHER = sccache",
    "CMAKE_CXX_COMPILER_LAUNCHER = sccache",
    "CMAKE_CUDA_COMPILER_LAUNCHER = sccache"
  )
} else {
  settings <- c(
    header,
    "CC := sccache $(CC)",
    "CXX := sccache $(CXX)",
    "CXX11 := sccache $(CXX11)",
    "CXX14 := sccache $(CXX14)",
    "CXX17 := sccache $(CXX17)",
    "CXX20 := sccache $(CXX20)"
  )
}
writeLines(settings, makevars)
