# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/jvm-packages"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
  - package-ecosystem: "maven"
    directory: "/jvm-packages/xgboost4j"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
  - package-ecosystem: "maven"
    directory: "/jvm-packages/xgboost4j-gpu"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
  - package-ecosystem: "maven"
    directory: "/jvm-packages/xgboost4j-example"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
  - package-ecosystem: "maven"
    directory: "/jvm-packages/xgboost4j-spark"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
      # Pin Spark version
      - dependency-name: "org.apache.spark:spark-core_2.12"
      - dependency-name: "org.apache.spark:spark-sql_2.12"
      - dependency-name: "org.apache.spark:spark-mllib_2.12"
  - package-ecosystem: "maven"
    directory: "/jvm-packages/xgboost4j-spark-gpu"
    schedule:
      interval: "daily"
    ignore:
      # Pin Scala version
      - dependency-name: "org.scala-lang:scala-compiler"
      - dependency-name: "org.scala-lang:scala-reflect"
      - dependency-name: "org.scala-lang:scala-library"
      # Pin Spark version
      - dependency-name: "org.apache.spark:spark-core_2.12"
      - dependency-name: "org.apache.spark:spark-sql_2.12"
      - dependency-name: "org.apache.spark:spark-mllib_2.12"
