# Custom images with CUDA toolkit installed
# See ops/packer for instructions for building the images
images:
  linux-amd64:
    platform: "linux"
    arch: "x64"
    owner: "492475357299"  # XGBooost CI
    name: "xgboost-ci-runs-on-linux-*"
  windows-amd64:
    platform: "windows"
    arch: "x64"
    owner: "492475357299"  # XGBooost CI
    name: "xgboost-ci-runs-on-windows-*"

runners:
  linux-amd64-cpu:
    cpu: 16
    family: ["c7i-flex", "c7i", "c7a", "c5", "c5a"]
    image: linux-amd64
  linux-amd64-gpu:
    family: ["g4dn.xlarge"]
    image: linux-amd64
  linux-amd64-mgpu:
    family: ["g4dn.12xlarge"]
    image: linux-amd64
  linux-arm64-cpu:
    cpu: 16
    family: ["c6g", "c7g"]
    image: ubuntu24-full-arm64
  windows-gpu:
    family: ["g4dn.2xlarge"]
    image: windows-amd64
  windows-cpu:
    cpu: 32
    family: ["c7i-flex", "c7i", "c7a", "c5", "c5a"]
    image: windows-amd64

