name: "Setup miniforge"
inputs:
  environment-name:
    description: "Name of Conda environment"
    required: true
  environment-file:
    description: "Path to environment file"
    required: true
runs:
  using: "composite"
  steps:
   - uses: conda-incubator/setup-miniconda@v3
     with:
       miniforge-variant: Miniforge3
       miniforge-version: latest
       activate-environment: ${{ inputs.environment-name }}
       environment-file: ${{ inputs.environment-file }}
       use-mamba: true
       auto-update-conda: true
    - name: Display Conda env
      shell: bash -el {0}
      run: |
        conda info
        conda list
