#' Generate plot of a single tree
#'
#' @param model dump generated by the \code{xgb.train} function.
#' @param feature_names names of each feature as a \code{character} vector. Can be extracted from a sparse matrix (see example). If model dump already contains feature names, this argument should be \code{NULL}.
#' @param plot_width width in pixels of the graph to produce
#' @param plot_height height in pixels of the graph to produce
#' @param ... currently not used
#' 
#' @return A diagram of the single tree
#' 
#' @details
#' 
#' For a gradient boosted tree ensemble of 10 rounds there are 10 trees that 
#' can be represented visually by this function.
#'
#' @examples
#' data(agaricus.train, package='xgboost')
#'
#' bst <- xgboost(data = agaricus.train$data, label = agaricus.train$label, max_depth = 15,
#'                  eta = 1, nthread = 2, nrounds = 30, objective = "binary:logistic",
#'                  min_child_weight = 50)
#'
#' p <- xgb.plot.single.trees(model = bst, feature_names = colnames(agaricus.train$data))
#' print(p)
#'
#' @export

xgb.plot.single.tree <- function(model, feature_names, tree, plot_width = NULL, plot_height = NULL, ...) {
  check.deprecation(...)

  allTrees <- xgb.model.dt.tree(feature_names = feature_names, model = model)
  
  allTrees <- allTrees[Tree == tree,]

  allTrees <- data.table(allTrees)
  
  allTrees[, `:=`(label, paste0(Feature, "\nCover: ", Cover, "\nGain: ", Quality))]
  allTrees[, `:=`(shape, "rectangle")][Feature == "Leaf", `:=`(shape, "oval")]
  
  allTrees[, `:=`(filledcolor, "Beige")][Feature == "Leaf", `:=`(filledcolor, "Khaki")]
  
  nodes <- DiagrammeR::create_nodes(nodes = allTrees[, ID] %>% 
          rev, label = allTrees[, label] %>% rev, style = "filled", 
          color = "DimGray", fillcolor = allTrees[, filledcolor] %>% 
              rev, shape = allTrees[, shape] %>% rev, data = allTrees[, 
              Feature] %>% rev, fontname = "Helvetica")
  
  edges <- DiagrammeR::create_edges(from = allTrees[Feature != 
      "Leaf", c(ID)] %>% rep(2), to = allTrees[Feature != "Leaf", 
      c(Yes, No)], label = allTrees[Feature != "Leaf", paste("<", 
      Split)] %>% c(rep("", nrow(allTrees[Feature != "Leaf"]))), 
      color = "DimGray", arrowsize = "1.5", arrowhead = "vee", 
      fontname = "Helvetica", rel = "leading_to")
  
  graph <- DiagrammeR::create_graph(nodes_df = nodes, edges_df = edges, 
      graph_attrs = "rankdir = LR")
  
  DiagrammeR::render_graph(graph, width = plot_width, height = plot_height)
}


