name: XGBoost CI (Lint)

on:
  push:
    branches:
      - master
      - 'release_*'
  pull_request:

permissions:
  contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: >-
    ${{ github.event.pull_request.number && 'PR-' }}${{ github.event.pull_request.number || github.ref_name }}

jobs:
  ci-configure:
    name: Configure variables for CI
    uses: ./.github/workflows/ci_configure.yml
    with:
      tag-prefix: lint

  clang-tidy:
    name: Run clang-tidy
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=linux-amd64-cpu
      - tag=lint-clang-tidy
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: "true"
      - name: Log into Docker registry (AWS ECR)
        run: bash ops/pipeline/login-docker-registry.sh
      - run: bash ops/pipeline/run-clang-tidy.sh

  clang-tidy-clang-cuda:
    name: Run clang-tidy from clang-CUDA compile DB
    needs: ci-configure
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=linux-amd64-cpu
      - tag=lint-clang-tidy-clang-cuda
    container:
      image: ${{ needs.ci-configure.outputs.docker_registry }}/xgb-ci.gpu_build_rockylinux8:${{ needs.ci-configure.outputs.image_tag }}
      credentials:
        username: ${{ needs.ci-configure.outputs.docker_username }}
        password: ${{ needs.ci-configure.outputs.docker_password }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: "true"
      - name: Run clang-tidy on clang-CUDA compile database
        run: bash ops/pipeline/run-clang-tidy-clang-cuda.sh

  python-mypy:
    runs-on: ubuntu-latest
    name: Type checks for the Python package
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: 'true'
      - uses: dmlc/xgboost-devops/actions/miniforge-setup@main
        with:
          environment-name: python_lint
          environment-file: ops/conda_env/python_lint.yml
      - name: Run mypy
        shell: bash -el {0}
        run: |
          python ops/script/type_check_python.py
