name: Nextgen XGBoost CI, MacOS

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: >-
    ${{ github.event.pull_request.number && 'PR-' }}${{ github.event.pull_request.number || github.ref_name }}

jobs:
  mac-m1-jvm:
    name: "Build libxgboost4j.dylib for MacOS M1"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - run: bash ops/pipeline/build-jvm-macos-m1.sh
