# Run expensive R tests with the help of rhub. Only triggered by a pull request review
# See discussion at https://github.com/dmlc/xgboost/pull/6378

name: XGBoost-R-Rhub

on:
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test-Rhub-noLD:
    if: github.event.comment.body == '/gha run rhub-test' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
    timeout-minutes: 120
    runs-on: ubuntu-latest
    container: rhub/debian-gcc-devel-nold
    steps:
    - name: Install git and system packages
      shell: bash
      run: |
        sudo apt update && sudo apt install libcurl4-openssl-dev libssl-dev libssh2-1-dev libgit2-dev pandoc pandoc-citeproc libglpk-dev libxml2-dev libharfbuzz-dev libfribidi-dev git -y

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        /tmp/R-devel/bin/Rscript -e "source('./R-package/tests/helper_scripts/install_deps.R')"


    - name: Run R tests
      shell: bash
      run: |
        cd R-package && \
        /tmp/R-devel/bin/R CMD INSTALL . && \
        /tmp/R-devel/bin/R -q -e "library(testthat); setwd('tests'); source('testthat.R')"

  test-Rhub-debian:
    if: github.event.comment.body == '/gha run rhub-test' && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association)
    timeout-minutes: 120
    runs-on: ubuntu-latest
    container: rhub/debian-gcc-devel

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}

    steps:
    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install libcurl4-openssl-dev libssl-dev libssh2-1-dev libgit2-dev pandoc pandoc-citeproc libglpk-dev libxml2-dev libharfbuzz-dev libfribidi-dev git -y

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        /tmp/R-devel/bin/Rscript -e "source('./R-package/tests/helper_scripts/install_deps.R')"

    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        architecture: 'x64'

    - name: Build R
      shell: bash -l {0}
      run: |
        python tests/ci_build/test_r_package.py --r=/tmp/R-devel/bin/R --compiler=mingw --build-tool=autotools --task=check
