name: XGBoost CI (oneAPI)

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: >-
    ${{ github.event.pull_request.number && 'PR-' }}${{ github.event.pull_request.number || github.ref_name }}

jobs:
  gtest-cpu-sycl:
    name: Test Google C++ unittest (CPU SYCL)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: linux_sycl_test
        environment-file: ops/conda_env/linux_sycl_test.yml
        use-mamba: true
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Build and install XGBoost
      run: |
        bash ops/script/build_via_cmake.sh --conda-env=linux_sycl_test -DPLUGIN_SYCL=ON
    - name: Run gtest
      run: ./build/testxgboost

  python-sycl-tests-on-ubuntu:
    name: Test XGBoost Python package with SYCL
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: linux_sycl_test
          environment-file: ops/conda_env/linux_sycl_test.yml
          use-mamba: true
      - name: Display Conda env
        run: |
          conda info
          conda list
      - name: Build and install XGBoost
        run: |
          bash ops/script/build_via_cmake.sh --conda-env=linux_sycl_test -DPLUGIN_SYCL=ON
          cd python-package
          python --version
          pip install -v .
      - name: Test Python package
        run: pytest -s -v -rxXs --durations=0 ./tests/python-sycl/
