## List of CI containers with definitions and build arguments

# Each container will be built using the definition from
# ops/docker/dockerfile/Dockerfile.CONTAINER_DEF

rapids_versions:
  stable: &rapids_version "24.10"
  dev: &dev_rapids_version "24.12"

xgb-ci.gpu_build_rockylinux8:
  container_def: gpu_build_rockylinux8
  build_args:
    CUDA_VERSION_ARG: "12.4.1"
    NCCL_VERSION_ARG: "2.23.4-1"
    RAPIDS_VERSION_ARG: *rapids_version

xgb-ci.gpu:
  container_def: gpu
  build_args:
    CUDA_VERSION_ARG: "12.4.1"
    NCCL_VERSION_ARG: "2.23.4-1"
    RAPIDS_VERSION_ARG: *rapids_version

xgb-ci.manylinux_2_28_x86_64:
  container_def: manylinux_2_28_x86_64
